[package]
name = "tpch_polars"
version = "0.1.0"
edition = "2021"


[dependencies]
wake = { path = "../../../wake" }
itertools = "0.10"
log = "0.4.14"
jemallocator = "0.3.2"
glob = "0.3.0"
polars = { version = "0.23.2", features = ["parquet"] }
alphanumeric-sort = "1.4.4"
env_logger = "0.9.0"
