name: Rust CI (Benchmark)

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: nschloe/action-cached-lfs-checkout@v1
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Run Benchmarks
      run: cargo bench
      working-directory: rust/runtime/
